/* Exceptions are protected sections of code that are likely to go wrong
 * The protected code is insterted into the try{ } block.
 *
 * Exception types are identified at compile time, or discovered at runtime
 * They are then "Caught" through the catch{ } block.
 *
 */ The finally{ } block sweeps up anything and can either return or exit.

package toolbox;

public class Thrower{

	public static void main(String [] args)
	{
		try {
		   // Protected code
		} catch (ExceptionType1 e1) {
		   // Catch block
		} catch (ExceptionType2 e2) {
		   // Catch block
		} catch (ExceptionType3 e3) {
		   // Catch block
		}finally {
		   // The finally block always executes.
		}
	}
}
